version: "3.8"

services:
  fullstackapp:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    container_name: mongo-web-app
    volumes:
      - ./Frontend:/app
    working_dir: /app
    environment:
      - ASPNETCORE_URLS=http://*:5000
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:5000"
    command: bash -c "dotnet publish -c Release ./Frontend.csproj -o ./publish && dotnet ./publish/Frontend.dll"
  
